name: Shell Commands

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: multiline script
        run: |
          #!/usr/bin/env bash

          if [ -z "${GITHUB_BASE_REF}"] ;  then
            export GIT_PULL_REQUEST=false
            export GIT_BRANCH="${GITHUB_REF#refs/heads/}"         
          else :
            export GIT_PULL_REQUEST=true
            export GIT_BRANCH="${GITHUB_BASE_REF#refs/heads/}"            
          fi

          GIT_TAG=${GITHUB_REF#refs/tags/}
          #short id
          #GIT_COMMIT=""${GITHUB_SHA:0:7}""
          
          # Listing all Git Environment variables
          echo "Nameo of Workflow: $GITHUB_WORKFLOW"
          echo "Git Job ID: $GITHUB_JOB"
          echo "Git Event: $GITHUB_EVENT_NAME"
          echo "Git Tag: $GIT_TAG"
          echo "Git Repository: $GITHUB_REPOSITORY"
          echo "Git Branch: $GIT_BRANCH"
          echo "Git Workspace: $GITHUB_WORKSPACE"
          echo "Git Runner ID: $GITHUB_RUN_ID"
          echo "Git Runner Number: $GITHUB_RUN_NUMBER"
          echo "Git Sha Commit: $GITHUB_SHA"
          echo "Git Commit: $GIT_COMMIT"
          echo "Git Pull Request: $GIT_PULL_REQUEST"          
          echo "Git PR Head Branch: $GITHUB_HEAD_REF"
          echo "Git PR Base Branch: $GITHUB_BASE_REF"

