name: Shell Commands

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: multiline script
        run: |
          #!/usr/bin/env bash
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          if [ -z "${GITHUB_BASE_REF}"] ;  then
            echo "Git Pull Request: false"
            export GIT_PULL_REQUEST=true            
          else :
            echo "Git Pull Request: true"
            export GIT_PULL_REQUEST=true            
          fi
          echo "Github Repository: $GITHUB_REPOSITORY"

          export GIT_BRANCH="${GITHUB_REF#refs/heads/}"
          echo "Git Branch: $GIT_BRANCH"

          echo "Git Workspace: $GITHUB_WORKSPACE"
